# Service的名字, 必选
Name = "redis_idiary"

# 各种自定义的参数, 会以 Option 的方式放到 Redis 中, 全部非必选
# 连接超时
ConnTimeOut = 1000
# 写数据超时
WriteTimeOut = 500
# 读数据超时
ReadTimeOut = 500
# 请求失败后的重试次数: 总请求次数 = Retry + 1
Retry = 2

# 资源定位: 手动配置 - 使用IP、端口
[Resource.Manual]
[[Resource.Manual.default]]
Host = "localhost"
Port = 6379

# redis必要配置, 这一项必须要有
# 连接池使用go-redis带的连接池, 每个ip+端口分配一个连接池
[Redis]
# DB 可选
DB = 0
# PoolSizePerIP 每个实例pool连接容量, 可选
PoolSizePerIP	= 10
# MinIdleConnsPerIP 每个实例pool初始连接个数, 可选
MinIdleConnsPerIP	= 5