name: Go

on:
  push:
    branches: [ liziwei01-patch-1 ]
  pull_request:
    branches: [ liziwei01-patch-1 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go mod tidy && go build -v ./back-end/gin-idiary-appui/

    - name: Test
      run: go mod tidy && go test -v ./back-end/gin-idiary-appui/
